apiVersion: v1
kind: Service
metadata:
  name: {{ include "rest-api-cbr-chart.fullname" . }}
  labels:
    app: {{ include "rest-api-cbr-chart.name" . }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.port }}
      protocol: TCP
      name: http
  selector:
    {{ include "rest-api-cbr-chart.name" . }}
