apiVersion: apps/v1
kind: Deployment
metadata:
  name: rest-api-cbr
  labels:
    rest-api-cbr: rest-api-cbr

spec:
  replicas: 2
  selector:
    matchLabels:
      rest-api-cbr: rest-api-cbr
  template:
    metadata:
      labels:
        rest-api-cbr: rest-api-cbr
    spec:
      containers:
      - name: rest-api-cbr
        image: gberdyshev/rest-api-cbr:1.0.1
        ports:
          - containerPort: 8000
        resources:
          requests:
            cpu: 0.5
          limits:
            memory: 256Mi