apiVersion: v1
kind: Service
metadata:
  labels:
    rest-api-cbr: rest-api-cbr
  name: rest-api-cbr
spec:
  ports:
  - port: 8000
    protocol: TCP
    targetPort: 8000
  selector:
    rest-api-cbr: rest-api-cbr
  type: NodePort
